module: KituraSession
author: IBM
github_url: https://github.com/IBM-Swift/Kitura-Session/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Kitura-Session.xcodeproj, -target, KituraSession, -toolchain, org.swift.3020160823a, LIBRARY_SEARCH_PATHS=.build/debug]

